trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    displayName: 'Install dependencies and build'

  - task: AWSCLI@1
    inputs:
      awsCredentials: 'MyAwsServiceConnection'
      regionName: 'ap-southeast-2'
    displayName: 'Configure AWS credentials'

  - script: |
      npx cdk synth
    displayName: 'CDK Synth'

  - script: |
      npx cdk deploy --require-approval never
    displayName: 'CDK Deploy'
